### ISSUE TITLE
Single paddle drive

### ISSUE THREAD

**Issue by UWSElectrical** [stuff1993/UWS_Solar_2015#17]
Auto regen with no throttle input
Allow for regen paddle to be disconnected

**Comment by UWSElectrical** [comment]
Add multiple drive modes + corresponding dick modes
- Regen and throttle paddles
- Throttle paddle, regen with no input
- Single paddle with throttle regen

**Comment by stuff1993** [comment]
Add new option selector in options screen for paddle mode

**Comment by stuff1993** [comment]
Paddle modes maintained in main_paddles
Select paddle mode from Options Menu
