### ISSUE TITLE
HV Control

### ISSUE THREAD

**Issue by stuff1993** [stuff1993/UWS_Solar_2015#6]
Control HV contactor with ARMED pin

**Comment by stuff1993** [comment]
To test

**Comment by Mazzaa** [comment]
Check this holds pin high

**Comment by stuff1993** [comment]
Check HV in main loop.

void check_HV (void)
{
uint16_t V_GOOD_COUNTER;

if(ESC.Bus_V > 100 && V_GOOD_COUNTER<1100){V_GOOD_COUNTER++;}
else if(V_GOOD_COUNTER)(V_GOOD_COUNTER--;}

if(V_GOOD_COUNTER>1000 && !STATS.ARMED){buzzer(1000);STATS.ARMED = ON;HV_ON;}
else if(V_GOOD_COUNTER<100){STATS.ARMED = OFF;HV_OFF;}
}

**Comment by stuff1993** [comment]
Implemented in menu loop with BMU voltage comparison
